/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorIndexRouteImport } from './routes/error.index'
import { Route as ErrorTimeoutRouteImport } from './routes/error.timeout'
import { Route as ErrorServerRouteImport } from './routes/error.server'
import { Route as ErrorRateLimitRouteImport } from './routes/error.rate-limit'
import { Route as ErrorPatientNotFoundRouteImport } from './routes/error.patient-not-found'
import { Route as ErrorOfflineRouteImport } from './routes/error.offline'
import { Route as ErrorOcrFailedRouteImport } from './routes/error.ocr-failed'
import { Route as ErrorNotFoundRouteImport } from './routes/error.not-found'
import { Route as ErrorMaintenanceRouteImport } from './routes/error.maintenance'
import { Route as ErrorLlmOfflineRouteImport } from './routes/error.llm-offline'
import { Route as ErrorInsufficientEvidenceRouteImport } from './routes/error.insufficient-evidence'
import { Route as ErrorHmsUnreachableRouteImport } from './routes/error.hms-unreachable'
import { Route as ErrorForbiddenRouteImport } from './routes/error.forbidden'
import { Route as ErrorConflictRouteImport } from './routes/error.conflict'
import { Route as ErrorAuthenticationRequiredRouteImport } from './routes/error.authentication-required'
import { Route as AuthSessionExpiredRouteImport } from './routes/auth.session-expired'
import { Route as AuthMfaRouteImport } from './routes/auth.mfa'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScreensRouteImport } from './routes/_app.screens'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMetricsRouteImport } from './routes/_app.metrics'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAccessPolicyRouteImport } from './routes/_app.access-policy'
import { Route as AppTimelineIndexRouteImport } from './routes/_app.timeline.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppPatientsIndexRouteImport } from './routes/_app.patients.index'
import { Route as AppMetricsIndexRouteImport } from './routes/_app.metrics.index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app.documents.index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppAuditIndexRouteImport } from './routes/_app.audit.index'
import { Route as AppAccessRequestsIndexRouteImport } from './routes/_app.access-requests.index'
import { Route as AuthSsoCallbackRouteImport } from './routes/auth.sso.callback'
import { Route as AppTimelineEventIdRouteImport } from './routes/_app.timeline.$eventId'
import { Route as AppSettingsWorkspacesRouteImport } from './routes/_app.settings.workspaces'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppSettingsDisplayRouteImport } from './routes/_app.settings.display'
import { Route as AppSettingsAiRouteImport } from './routes/_app.settings.ai'
import { Route as AppPharmacyReviewQueueRouteImport } from './routes/_app.pharmacy.review-queue'
import { Route as AppPatientsPatientIdRouteImport } from './routes/_app.patients.$patientId'
import { Route as AppMetricsWorkflowsRouteImport } from './routes/_app.metrics.workflows'
import { Route as AppMetricsSafeRefusalRouteImport } from './routes/_app.metrics.safe-refusal'
import { Route as AppMetricsFeedbackRouteImport } from './routes/_app.metrics.feedback'
import { Route as AppMetricsConfigRouteImport } from './routes/_app.metrics.config'
import { Route as AppMetricsCitationsRouteImport } from './routes/_app.metrics.citations'
import { Route as AppMedicationConflictsConflictIdRouteImport } from './routes/_app.medication-conflicts.$conflictId'
import { Route as AppIntegrationsVectorIndexRouteImport } from './routes/_app.integrations.vector-index'
import { Route as AppIntegrationsLlmRouteImport } from './routes/_app.integrations.llm'
import { Route as AppIntegrationsHmsRouteImport } from './routes/_app.integrations.hms'
import { Route as AppHelpShortcutsRouteImport } from './routes/_app.help.shortcuts'
import { Route as AppHelpDiagnosticsRouteImport } from './routes/_app.help.diagnostics'
import { Route as AppDocumentsUploadRouteImport } from './routes/_app.documents.upload'
import { Route as AppDocumentsSyncHmsRouteImport } from './routes/_app.documents.sync-hms'
import { Route as AppDocumentsSearchRouteImport } from './routes/_app.documents.search'
import { Route as AppDocumentsOcrQueueRouteImport } from './routes/_app.documents.ocr-queue'
import { Route as AppDocumentsDuplicatesRouteImport } from './routes/_app.documents.duplicates'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/_app.documents.$documentId'
import { Route as AppDashboardCustomizeRouteImport } from './routes/_app.dashboard.customize'
import { Route as AppDashboardActivityRouteImport } from './routes/_app.dashboard.activity'
import { Route as AppCitationsCompareRouteImport } from './routes/_app.citations.compare'
import { Route as AppCitationsSourceIdRouteImport } from './routes/_app.citations.$sourceId'
import { Route as AppChatTemplatesRouteImport } from './routes/_app.chat.templates'
import { Route as AppChatNewRouteImport } from './routes/_app.chat.new'
import { Route as AppChatHistoryRouteImport } from './routes/_app.chat.history'
import { Route as AppChatGeneralRouteImport } from './routes/_app.chat.general'
import { Route as AppAuditExportRouteImport } from './routes/_app.audit.export'
import { Route as AppAuditDeniedRouteImport } from './routes/_app.audit.denied'
import { Route as AppAuditComplianceSummaryRouteImport } from './routes/_app.audit.compliance-summary'
import { Route as AppAdminRolesRouteImport } from './routes/_app.admin.roles'
import { Route as AppAdminDataRetentionRouteImport } from './routes/_app.admin.data-retention'
import { Route as AppAdminAbacRouteImport } from './routes/_app.admin.abac'
import { Route as AppAccessRequestsRequestIdRouteImport } from './routes/_app.access-requests.$requestId'
import { Route as AppPatientsPatientIdIndexRouteImport } from './routes/_app.patients.$patientId.index'
import { Route as AppPatientsPatientIdTimelineRouteImport } from './routes/_app.patients.$patientId.timeline'
import { Route as AppPatientsPatientIdRefreshRouteImport } from './routes/_app.patients.$patientId.refresh'
import { Route as AppPatientsPatientIdOverviewRouteImport } from './routes/_app.patients.$patientId.overview'
import { Route as AppPatientsPatientIdMedicationsRouteImport } from './routes/_app.patients.$patientId.medications'
import { Route as AppPatientsPatientIdMedicationReviewRouteImport } from './routes/_app.patients.$patientId.medication-review'
import { Route as AppPatientsPatientIdLabsRouteImport } from './routes/_app.patients.$patientId.labs'
import { Route as AppPatientsPatientIdDocumentsRouteImport } from './routes/_app.patients.$patientId.documents'
import { Route as AppPatientsPatientIdAccessHistoryRouteImport } from './routes/_app.patients.$patientId.access-history'
import { Route as AppIntegrationsTracesTraceIdRouteImport } from './routes/_app.integrations.traces.$traceId'
import { Route as AppIntegrationsHmsDlqRouteImport } from './routes/_app.integrations.hms.dlq'
import { Route as AppGraphPatientsPatientIdRouteImport } from './routes/_app.graph.patients.$patientId'
import { Route as AppGraphPathPathIdRouteImport } from './routes/_app.graph.path.$pathId'
import { Route as AppDocumentsDocumentIdReviewRouteImport } from './routes/_app.documents.$documentId.review'
import { Route as AppDocumentsDocumentIdRetryRouteImport } from './routes/_app.documents.$documentId.retry'
import { Route as AppDocumentsDocumentIdEditRouteImport } from './routes/_app.documents.$documentId.edit'
import { Route as AppChatPatientsPatientIdRouteImport } from './routes/_app.chat.patients.$patientId'
import { Route as AppAuditTracesTraceIdRouteImport } from './routes/_app.audit.traces.$traceId'
import { Route as AppAuditEventIdRawRouteImport } from './routes/_app.audit.$eventId.raw'
import { Route as AppAccessRequestsRequestIdReviewRouteImport } from './routes/_app.access-requests.$requestId.review'
import { Route as AppIntegrationsHmsJobsJobIdRouteImport } from './routes/_app.integrations.hms.jobs.$jobId'
import { Route as AppIntegrationsHmsPatientsPatientIdSyncRouteImport } from './routes/_app.integrations.hms.patients.$patientId.sync'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorTimeoutRoute = ErrorTimeoutRouteImport.update({
  id: '/error/timeout',
  path: '/error/timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorServerRoute = ErrorServerRouteImport.update({
  id: '/error/server',
  path: '/error/server',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRateLimitRoute = ErrorRateLimitRouteImport.update({
  id: '/error/rate-limit',
  path: '/error/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorPatientNotFoundRoute = ErrorPatientNotFoundRouteImport.update({
  id: '/error/patient-not-found',
  path: '/error/patient-not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorOfflineRoute = ErrorOfflineRouteImport.update({
  id: '/error/offline',
  path: '/error/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorOcrFailedRoute = ErrorOcrFailedRouteImport.update({
  id: '/error/ocr-failed',
  path: '/error/ocr-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorNotFoundRoute = ErrorNotFoundRouteImport.update({
  id: '/error/not-found',
  path: '/error/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorMaintenanceRoute = ErrorMaintenanceRouteImport.update({
  id: '/error/maintenance',
  path: '/error/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorLlmOfflineRoute = ErrorLlmOfflineRouteImport.update({
  id: '/error/llm-offline',
  path: '/error/llm-offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorInsufficientEvidenceRoute =
  ErrorInsufficientEvidenceRouteImport.update({
    id: '/error/insufficient-evidence',
    path: '/error/insufficient-evidence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ErrorHmsUnreachableRoute = ErrorHmsUnreachableRouteImport.update({
  id: '/error/hms-unreachable',
  path: '/error/hms-unreachable',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorForbiddenRoute = ErrorForbiddenRouteImport.update({
  id: '/error/forbidden',
  path: '/error/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorConflictRoute = ErrorConflictRouteImport.update({
  id: '/error/conflict',
  path: '/error/conflict',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorAuthenticationRequiredRoute =
  ErrorAuthenticationRequiredRouteImport.update({
    id: '/error/authentication-required',
    path: '/error/authentication-required',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSessionExpiredRoute = AuthSessionExpiredRouteImport.update({
  id: '/auth/session-expired',
  path: '/auth/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScreensRoute = AppScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessPolicyRoute = AppAccessPolicyRouteImport.update({
  id: '/access-policy',
  path: '/access-policy',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineIndexRoute = AppTimelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTimelineRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPatientsRoute,
} as any)
const AppMetricsIndexRoute = AppMetricsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMetricsRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAccessRequestsIndexRoute = AppAccessRequestsIndexRouteImport.update({
  id: '/access-requests/',
  path: '/access-requests/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/auth/sso/callback',
  path: '/auth/sso/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimelineEventIdRoute = AppTimelineEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppTimelineRoute,
} as any)
const AppSettingsWorkspacesRoute = AppSettingsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDisplayRoute = AppSettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPharmacyReviewQueueRoute = AppPharmacyReviewQueueRouteImport.update({
  id: '/pharmacy/review-queue',
  path: '/pharmacy/review-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => AppPatientsRoute,
} as any)
const AppMetricsWorkflowsRoute = AppMetricsWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppMetricsRoute,
} as any)
const AppMetricsSafeRefusalRoute = AppMetricsSafeRefusalRouteImport.update({
  id: '/safe-refusal',
  path: '/safe-refusal',
  getParentRoute: () => AppMetricsRoute,
} as any)
const AppMetricsFeedbackRoute = AppMetricsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppMetricsRoute,
} as any)
const AppMetricsConfigRoute = AppMetricsConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppMetricsRoute,
} as any)
const AppMetricsCitationsRoute = AppMetricsCitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => AppMetricsRoute,
} as any)
const AppMedicationConflictsConflictIdRoute =
  AppMedicationConflictsConflictIdRouteImport.update({
    id: '/medication-conflicts/$conflictId',
    path: '/medication-conflicts/$conflictId',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsVectorIndexRoute =
  AppIntegrationsVectorIndexRouteImport.update({
    id: '/integrations/vector-index',
    path: '/integrations/vector-index',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsLlmRoute = AppIntegrationsLlmRouteImport.update({
  id: '/integrations/llm',
  path: '/integrations/llm',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsHmsRoute = AppIntegrationsHmsRouteImport.update({
  id: '/integrations/hms',
  path: '/integrations/hms',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpShortcutsRoute = AppHelpShortcutsRouteImport.update({
  id: '/help/shortcuts',
  path: '/help/shortcuts',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpDiagnosticsRoute = AppHelpDiagnosticsRouteImport.update({
  id: '/help/diagnostics',
  path: '/help/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsUploadRoute = AppDocumentsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDocumentsSyncHmsRoute = AppDocumentsSyncHmsRouteImport.update({
  id: '/sync-hms',
  path: '/sync-hms',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDocumentsSearchRoute = AppDocumentsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDocumentsOcrQueueRoute = AppDocumentsOcrQueueRouteImport.update({
  id: '/ocr-queue',
  path: '/ocr-queue',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDocumentsDuplicatesRoute = AppDocumentsDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDashboardCustomizeRoute = AppDashboardCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardActivityRoute = AppDashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppCitationsCompareRoute = AppCitationsCompareRouteImport.update({
  id: '/citations/compare',
  path: '/citations/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppCitationsSourceIdRoute = AppCitationsSourceIdRouteImport.update({
  id: '/citations/$sourceId',
  path: '/citations/$sourceId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatTemplatesRoute = AppChatTemplatesRouteImport.update({
  id: '/chat/templates',
  path: '/chat/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppChatNewRoute = AppChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => AppRoute,
} as any)
const AppChatHistoryRoute = AppChatHistoryRouteImport.update({
  id: '/chat/history',
  path: '/chat/history',
  getParentRoute: () => AppRoute,
} as any)
const AppChatGeneralRoute = AppChatGeneralRouteImport.update({
  id: '/chat/general',
  path: '/chat/general',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditExportRoute = AppAuditExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAuditDeniedRoute = AppAuditDeniedRouteImport.update({
  id: '/denied',
  path: '/denied',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAuditComplianceSummaryRoute =
  AppAuditComplianceSummaryRouteImport.update({
    id: '/compliance-summary',
    path: '/compliance-summary',
    getParentRoute: () => AppAuditRoute,
  } as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDataRetentionRoute = AppAdminDataRetentionRouteImport.update({
  id: '/admin/data-retention',
  path: '/admin/data-retention',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAbacRoute = AppAdminAbacRouteImport.update({
  id: '/admin/abac',
  path: '/admin/abac',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRequestsRequestIdRoute =
  AppAccessRequestsRequestIdRouteImport.update({
    id: '/access-requests/$requestId',
    path: '/access-requests/$requestId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdIndexRoute =
  AppPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppPatientsPatientIdTimelineRoute =
  AppPatientsPatientIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppPatientsPatientIdRefreshRoute =
  AppPatientsPatientIdRefreshRouteImport.update({
    id: '/refresh',
    path: '/refresh',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppPatientsPatientIdOverviewRoute =
  AppPatientsPatientIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppPatientsPatientIdMedicationsRoute =
  AppPatientsPatientIdMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppPatientsPatientIdMedicationReviewRoute =
  AppPatientsPatientIdMedicationReviewRouteImport.update({
    id: '/medication-review',
    path: '/medication-review',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppPatientsPatientIdLabsRoute =
  AppPatientsPatientIdLabsRouteImport.update({
    id: '/labs',
    path: '/labs',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppPatientsPatientIdDocumentsRoute =
  AppPatientsPatientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppPatientsPatientIdAccessHistoryRoute =
  AppPatientsPatientIdAccessHistoryRouteImport.update({
    id: '/access-history',
    path: '/access-history',
    getParentRoute: () => AppPatientsPatientIdRoute,
  } as any)
const AppIntegrationsTracesTraceIdRoute =
  AppIntegrationsTracesTraceIdRouteImport.update({
    id: '/integrations/traces/$traceId',
    path: '/integrations/traces/$traceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsHmsDlqRoute = AppIntegrationsHmsDlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => AppIntegrationsHmsRoute,
} as any)
const AppGraphPatientsPatientIdRoute =
  AppGraphPatientsPatientIdRouteImport.update({
    id: '/graph/patients/$patientId',
    path: '/graph/patients/$patientId',
    getParentRoute: () => AppRoute,
  } as any)
const AppGraphPathPathIdRoute = AppGraphPathPathIdRouteImport.update({
  id: '/graph/path/$pathId',
  path: '/graph/path/$pathId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsDocumentIdReviewRoute =
  AppDocumentsDocumentIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AppDocumentsDocumentIdRoute,
  } as any)
const AppDocumentsDocumentIdRetryRoute =
  AppDocumentsDocumentIdRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => AppDocumentsDocumentIdRoute,
  } as any)
const AppDocumentsDocumentIdEditRoute =
  AppDocumentsDocumentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppDocumentsDocumentIdRoute,
  } as any)
const AppChatPatientsPatientIdRoute =
  AppChatPatientsPatientIdRouteImport.update({
    id: '/chat/patients/$patientId',
    path: '/chat/patients/$patientId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuditTracesTraceIdRoute = AppAuditTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAuditEventIdRawRoute = AppAuditEventIdRawRouteImport.update({
  id: '/$eventId/raw',
  path: '/$eventId/raw',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAccessRequestsRequestIdReviewRoute =
  AppAccessRequestsRequestIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AppAccessRequestsRequestIdRoute,
  } as any)
const AppIntegrationsHmsJobsJobIdRoute =
  AppIntegrationsHmsJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AppIntegrationsHmsRoute,
  } as any)
const AppIntegrationsHmsPatientsPatientIdSyncRoute =
  AppIntegrationsHmsPatientsPatientIdSyncRouteImport.update({
    id: '/patients/$patientId/sync',
    path: '/patients/$patientId/sync',
    getParentRoute: () => AppIntegrationsHmsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-policy': typeof AppAccessPolicyRoute
  '/audit': typeof AppAuditRouteWithChildren
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/documents': typeof AppDocumentsRouteWithChildren
  '/metrics': typeof AppMetricsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRouteWithChildren
  '/screens': typeof AppScreensRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/timeline': typeof AppTimelineRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/error/authentication-required': typeof ErrorAuthenticationRequiredRoute
  '/error/conflict': typeof ErrorConflictRoute
  '/error/forbidden': typeof ErrorForbiddenRoute
  '/error/hms-unreachable': typeof ErrorHmsUnreachableRoute
  '/error/insufficient-evidence': typeof ErrorInsufficientEvidenceRoute
  '/error/llm-offline': typeof ErrorLlmOfflineRoute
  '/error/maintenance': typeof ErrorMaintenanceRoute
  '/error/not-found': typeof ErrorNotFoundRoute
  '/error/ocr-failed': typeof ErrorOcrFailedRoute
  '/error/offline': typeof ErrorOfflineRoute
  '/error/patient-not-found': typeof ErrorPatientNotFoundRoute
  '/error/rate-limit': typeof ErrorRateLimitRoute
  '/error/server': typeof ErrorServerRoute
  '/error/timeout': typeof ErrorTimeoutRoute
  '/error/': typeof ErrorIndexRoute
  '/access-requests/$requestId': typeof AppAccessRequestsRequestIdRouteWithChildren
  '/admin/abac': typeof AppAdminAbacRoute
  '/admin/data-retention': typeof AppAdminDataRetentionRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/audit/compliance-summary': typeof AppAuditComplianceSummaryRoute
  '/audit/denied': typeof AppAuditDeniedRoute
  '/audit/export': typeof AppAuditExportRoute
  '/chat/general': typeof AppChatGeneralRoute
  '/chat/history': typeof AppChatHistoryRoute
  '/chat/new': typeof AppChatNewRoute
  '/chat/templates': typeof AppChatTemplatesRoute
  '/citations/$sourceId': typeof AppCitationsSourceIdRoute
  '/citations/compare': typeof AppCitationsCompareRoute
  '/dashboard/activity': typeof AppDashboardActivityRoute
  '/dashboard/customize': typeof AppDashboardCustomizeRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRouteWithChildren
  '/documents/duplicates': typeof AppDocumentsDuplicatesRoute
  '/documents/ocr-queue': typeof AppDocumentsOcrQueueRoute
  '/documents/search': typeof AppDocumentsSearchRoute
  '/documents/sync-hms': typeof AppDocumentsSyncHmsRoute
  '/documents/upload': typeof AppDocumentsUploadRoute
  '/help/diagnostics': typeof AppHelpDiagnosticsRoute
  '/help/shortcuts': typeof AppHelpShortcutsRoute
  '/integrations/hms': typeof AppIntegrationsHmsRouteWithChildren
  '/integrations/llm': typeof AppIntegrationsLlmRoute
  '/integrations/vector-index': typeof AppIntegrationsVectorIndexRoute
  '/medication-conflicts/$conflictId': typeof AppMedicationConflictsConflictIdRoute
  '/metrics/citations': typeof AppMetricsCitationsRoute
  '/metrics/config': typeof AppMetricsConfigRoute
  '/metrics/feedback': typeof AppMetricsFeedbackRoute
  '/metrics/safe-refusal': typeof AppMetricsSafeRefusalRoute
  '/metrics/workflows': typeof AppMetricsWorkflowsRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRouteWithChildren
  '/pharmacy/review-queue': typeof AppPharmacyReviewQueueRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/display': typeof AppSettingsDisplayRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/workspaces': typeof AppSettingsWorkspacesRoute
  '/timeline/$eventId': typeof AppTimelineEventIdRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/access-requests/': typeof AppAccessRequestsIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/chat/': typeof AppChatIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/metrics/': typeof AppMetricsIndexRoute
  '/patients/': typeof AppPatientsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/timeline/': typeof AppTimelineIndexRoute
  '/access-requests/$requestId/review': typeof AppAccessRequestsRequestIdReviewRoute
  '/audit/$eventId/raw': typeof AppAuditEventIdRawRoute
  '/audit/traces/$traceId': typeof AppAuditTracesTraceIdRoute
  '/chat/patients/$patientId': typeof AppChatPatientsPatientIdRoute
  '/documents/$documentId/edit': typeof AppDocumentsDocumentIdEditRoute
  '/documents/$documentId/retry': typeof AppDocumentsDocumentIdRetryRoute
  '/documents/$documentId/review': typeof AppDocumentsDocumentIdReviewRoute
  '/graph/path/$pathId': typeof AppGraphPathPathIdRoute
  '/graph/patients/$patientId': typeof AppGraphPatientsPatientIdRoute
  '/integrations/hms/dlq': typeof AppIntegrationsHmsDlqRoute
  '/integrations/traces/$traceId': typeof AppIntegrationsTracesTraceIdRoute
  '/patients/$patientId/access-history': typeof AppPatientsPatientIdAccessHistoryRoute
  '/patients/$patientId/documents': typeof AppPatientsPatientIdDocumentsRoute
  '/patients/$patientId/labs': typeof AppPatientsPatientIdLabsRoute
  '/patients/$patientId/medication-review': typeof AppPatientsPatientIdMedicationReviewRoute
  '/patients/$patientId/medications': typeof AppPatientsPatientIdMedicationsRoute
  '/patients/$patientId/overview': typeof AppPatientsPatientIdOverviewRoute
  '/patients/$patientId/refresh': typeof AppPatientsPatientIdRefreshRoute
  '/patients/$patientId/timeline': typeof AppPatientsPatientIdTimelineRoute
  '/patients/$patientId/': typeof AppPatientsPatientIdIndexRoute
  '/integrations/hms/jobs/$jobId': typeof AppIntegrationsHmsJobsJobIdRoute
  '/integrations/hms/patients/$patientId/sync': typeof AppIntegrationsHmsPatientsPatientIdSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-policy': typeof AppAccessPolicyRoute
  '/notifications': typeof AppNotificationsRoute
  '/screens': typeof AppScreensRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/error/authentication-required': typeof ErrorAuthenticationRequiredRoute
  '/error/conflict': typeof ErrorConflictRoute
  '/error/forbidden': typeof ErrorForbiddenRoute
  '/error/hms-unreachable': typeof ErrorHmsUnreachableRoute
  '/error/insufficient-evidence': typeof ErrorInsufficientEvidenceRoute
  '/error/llm-offline': typeof ErrorLlmOfflineRoute
  '/error/maintenance': typeof ErrorMaintenanceRoute
  '/error/not-found': typeof ErrorNotFoundRoute
  '/error/ocr-failed': typeof ErrorOcrFailedRoute
  '/error/offline': typeof ErrorOfflineRoute
  '/error/patient-not-found': typeof ErrorPatientNotFoundRoute
  '/error/rate-limit': typeof ErrorRateLimitRoute
  '/error/server': typeof ErrorServerRoute
  '/error/timeout': typeof ErrorTimeoutRoute
  '/error': typeof ErrorIndexRoute
  '/access-requests/$requestId': typeof AppAccessRequestsRequestIdRouteWithChildren
  '/admin/abac': typeof AppAdminAbacRoute
  '/admin/data-retention': typeof AppAdminDataRetentionRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/audit/compliance-summary': typeof AppAuditComplianceSummaryRoute
  '/audit/denied': typeof AppAuditDeniedRoute
  '/audit/export': typeof AppAuditExportRoute
  '/chat/general': typeof AppChatGeneralRoute
  '/chat/history': typeof AppChatHistoryRoute
  '/chat/new': typeof AppChatNewRoute
  '/chat/templates': typeof AppChatTemplatesRoute
  '/citations/$sourceId': typeof AppCitationsSourceIdRoute
  '/citations/compare': typeof AppCitationsCompareRoute
  '/dashboard/activity': typeof AppDashboardActivityRoute
  '/dashboard/customize': typeof AppDashboardCustomizeRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRouteWithChildren
  '/documents/duplicates': typeof AppDocumentsDuplicatesRoute
  '/documents/ocr-queue': typeof AppDocumentsOcrQueueRoute
  '/documents/search': typeof AppDocumentsSearchRoute
  '/documents/sync-hms': typeof AppDocumentsSyncHmsRoute
  '/documents/upload': typeof AppDocumentsUploadRoute
  '/help/diagnostics': typeof AppHelpDiagnosticsRoute
  '/help/shortcuts': typeof AppHelpShortcutsRoute
  '/integrations/hms': typeof AppIntegrationsHmsRouteWithChildren
  '/integrations/llm': typeof AppIntegrationsLlmRoute
  '/integrations/vector-index': typeof AppIntegrationsVectorIndexRoute
  '/medication-conflicts/$conflictId': typeof AppMedicationConflictsConflictIdRoute
  '/metrics/citations': typeof AppMetricsCitationsRoute
  '/metrics/config': typeof AppMetricsConfigRoute
  '/metrics/feedback': typeof AppMetricsFeedbackRoute
  '/metrics/safe-refusal': typeof AppMetricsSafeRefusalRoute
  '/metrics/workflows': typeof AppMetricsWorkflowsRoute
  '/pharmacy/review-queue': typeof AppPharmacyReviewQueueRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/display': typeof AppSettingsDisplayRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/workspaces': typeof AppSettingsWorkspacesRoute
  '/timeline/$eventId': typeof AppTimelineEventIdRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/access-requests': typeof AppAccessRequestsIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/chat': typeof AppChatIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/metrics': typeof AppMetricsIndexRoute
  '/patients': typeof AppPatientsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/timeline': typeof AppTimelineIndexRoute
  '/access-requests/$requestId/review': typeof AppAccessRequestsRequestIdReviewRoute
  '/audit/$eventId/raw': typeof AppAuditEventIdRawRoute
  '/audit/traces/$traceId': typeof AppAuditTracesTraceIdRoute
  '/chat/patients/$patientId': typeof AppChatPatientsPatientIdRoute
  '/documents/$documentId/edit': typeof AppDocumentsDocumentIdEditRoute
  '/documents/$documentId/retry': typeof AppDocumentsDocumentIdRetryRoute
  '/documents/$documentId/review': typeof AppDocumentsDocumentIdReviewRoute
  '/graph/path/$pathId': typeof AppGraphPathPathIdRoute
  '/graph/patients/$patientId': typeof AppGraphPatientsPatientIdRoute
  '/integrations/hms/dlq': typeof AppIntegrationsHmsDlqRoute
  '/integrations/traces/$traceId': typeof AppIntegrationsTracesTraceIdRoute
  '/patients/$patientId/access-history': typeof AppPatientsPatientIdAccessHistoryRoute
  '/patients/$patientId/documents': typeof AppPatientsPatientIdDocumentsRoute
  '/patients/$patientId/labs': typeof AppPatientsPatientIdLabsRoute
  '/patients/$patientId/medication-review': typeof AppPatientsPatientIdMedicationReviewRoute
  '/patients/$patientId/medications': typeof AppPatientsPatientIdMedicationsRoute
  '/patients/$patientId/overview': typeof AppPatientsPatientIdOverviewRoute
  '/patients/$patientId/refresh': typeof AppPatientsPatientIdRefreshRoute
  '/patients/$patientId/timeline': typeof AppPatientsPatientIdTimelineRoute
  '/patients/$patientId': typeof AppPatientsPatientIdIndexRoute
  '/integrations/hms/jobs/$jobId': typeof AppIntegrationsHmsJobsJobIdRoute
  '/integrations/hms/patients/$patientId/sync': typeof AppIntegrationsHmsPatientsPatientIdSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/access-policy': typeof AppAccessPolicyRoute
  '/_app/audit': typeof AppAuditRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/metrics': typeof AppMetricsRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/patients': typeof AppPatientsRouteWithChildren
  '/_app/screens': typeof AppScreensRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/timeline': typeof AppTimelineRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/error/authentication-required': typeof ErrorAuthenticationRequiredRoute
  '/error/conflict': typeof ErrorConflictRoute
  '/error/forbidden': typeof ErrorForbiddenRoute
  '/error/hms-unreachable': typeof ErrorHmsUnreachableRoute
  '/error/insufficient-evidence': typeof ErrorInsufficientEvidenceRoute
  '/error/llm-offline': typeof ErrorLlmOfflineRoute
  '/error/maintenance': typeof ErrorMaintenanceRoute
  '/error/not-found': typeof ErrorNotFoundRoute
  '/error/ocr-failed': typeof ErrorOcrFailedRoute
  '/error/offline': typeof ErrorOfflineRoute
  '/error/patient-not-found': typeof ErrorPatientNotFoundRoute
  '/error/rate-limit': typeof ErrorRateLimitRoute
  '/error/server': typeof ErrorServerRoute
  '/error/timeout': typeof ErrorTimeoutRoute
  '/error/': typeof ErrorIndexRoute
  '/_app/access-requests/$requestId': typeof AppAccessRequestsRequestIdRouteWithChildren
  '/_app/admin/abac': typeof AppAdminAbacRoute
  '/_app/admin/data-retention': typeof AppAdminDataRetentionRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/audit/compliance-summary': typeof AppAuditComplianceSummaryRoute
  '/_app/audit/denied': typeof AppAuditDeniedRoute
  '/_app/audit/export': typeof AppAuditExportRoute
  '/_app/chat/general': typeof AppChatGeneralRoute
  '/_app/chat/history': typeof AppChatHistoryRoute
  '/_app/chat/new': typeof AppChatNewRoute
  '/_app/chat/templates': typeof AppChatTemplatesRoute
  '/_app/citations/$sourceId': typeof AppCitationsSourceIdRoute
  '/_app/citations/compare': typeof AppCitationsCompareRoute
  '/_app/dashboard/activity': typeof AppDashboardActivityRoute
  '/_app/dashboard/customize': typeof AppDashboardCustomizeRoute
  '/_app/documents/$documentId': typeof AppDocumentsDocumentIdRouteWithChildren
  '/_app/documents/duplicates': typeof AppDocumentsDuplicatesRoute
  '/_app/documents/ocr-queue': typeof AppDocumentsOcrQueueRoute
  '/_app/documents/search': typeof AppDocumentsSearchRoute
  '/_app/documents/sync-hms': typeof AppDocumentsSyncHmsRoute
  '/_app/documents/upload': typeof AppDocumentsUploadRoute
  '/_app/help/diagnostics': typeof AppHelpDiagnosticsRoute
  '/_app/help/shortcuts': typeof AppHelpShortcutsRoute
  '/_app/integrations/hms': typeof AppIntegrationsHmsRouteWithChildren
  '/_app/integrations/llm': typeof AppIntegrationsLlmRoute
  '/_app/integrations/vector-index': typeof AppIntegrationsVectorIndexRoute
  '/_app/medication-conflicts/$conflictId': typeof AppMedicationConflictsConflictIdRoute
  '/_app/metrics/citations': typeof AppMetricsCitationsRoute
  '/_app/metrics/config': typeof AppMetricsConfigRoute
  '/_app/metrics/feedback': typeof AppMetricsFeedbackRoute
  '/_app/metrics/safe-refusal': typeof AppMetricsSafeRefusalRoute
  '/_app/metrics/workflows': typeof AppMetricsWorkflowsRoute
  '/_app/patients/$patientId': typeof AppPatientsPatientIdRouteWithChildren
  '/_app/pharmacy/review-queue': typeof AppPharmacyReviewQueueRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/display': typeof AppSettingsDisplayRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/workspaces': typeof AppSettingsWorkspacesRoute
  '/_app/timeline/$eventId': typeof AppTimelineEventIdRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/_app/access-requests/': typeof AppAccessRequestsIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/metrics/': typeof AppMetricsIndexRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/timeline/': typeof AppTimelineIndexRoute
  '/_app/access-requests/$requestId/review': typeof AppAccessRequestsRequestIdReviewRoute
  '/_app/audit/$eventId/raw': typeof AppAuditEventIdRawRoute
  '/_app/audit/traces/$traceId': typeof AppAuditTracesTraceIdRoute
  '/_app/chat/patients/$patientId': typeof AppChatPatientsPatientIdRoute
  '/_app/documents/$documentId/edit': typeof AppDocumentsDocumentIdEditRoute
  '/_app/documents/$documentId/retry': typeof AppDocumentsDocumentIdRetryRoute
  '/_app/documents/$documentId/review': typeof AppDocumentsDocumentIdReviewRoute
  '/_app/graph/path/$pathId': typeof AppGraphPathPathIdRoute
  '/_app/graph/patients/$patientId': typeof AppGraphPatientsPatientIdRoute
  '/_app/integrations/hms/dlq': typeof AppIntegrationsHmsDlqRoute
  '/_app/integrations/traces/$traceId': typeof AppIntegrationsTracesTraceIdRoute
  '/_app/patients/$patientId/access-history': typeof AppPatientsPatientIdAccessHistoryRoute
  '/_app/patients/$patientId/documents': typeof AppPatientsPatientIdDocumentsRoute
  '/_app/patients/$patientId/labs': typeof AppPatientsPatientIdLabsRoute
  '/_app/patients/$patientId/medication-review': typeof AppPatientsPatientIdMedicationReviewRoute
  '/_app/patients/$patientId/medications': typeof AppPatientsPatientIdMedicationsRoute
  '/_app/patients/$patientId/overview': typeof AppPatientsPatientIdOverviewRoute
  '/_app/patients/$patientId/refresh': typeof AppPatientsPatientIdRefreshRoute
  '/_app/patients/$patientId/timeline': typeof AppPatientsPatientIdTimelineRoute
  '/_app/patients/$patientId/': typeof AppPatientsPatientIdIndexRoute
  '/_app/integrations/hms/jobs/$jobId': typeof AppIntegrationsHmsJobsJobIdRoute
  '/_app/integrations/hms/patients/$patientId/sync': typeof AppIntegrationsHmsPatientsPatientIdSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-policy'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/metrics'
    | '/notifications'
    | '/patients'
    | '/screens'
    | '/settings'
    | '/timeline'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/session-expired'
    | '/error/authentication-required'
    | '/error/conflict'
    | '/error/forbidden'
    | '/error/hms-unreachable'
    | '/error/insufficient-evidence'
    | '/error/llm-offline'
    | '/error/maintenance'
    | '/error/not-found'
    | '/error/ocr-failed'
    | '/error/offline'
    | '/error/patient-not-found'
    | '/error/rate-limit'
    | '/error/server'
    | '/error/timeout'
    | '/error/'
    | '/access-requests/$requestId'
    | '/admin/abac'
    | '/admin/data-retention'
    | '/admin/roles'
    | '/audit/compliance-summary'
    | '/audit/denied'
    | '/audit/export'
    | '/chat/general'
    | '/chat/history'
    | '/chat/new'
    | '/chat/templates'
    | '/citations/$sourceId'
    | '/citations/compare'
    | '/dashboard/activity'
    | '/dashboard/customize'
    | '/documents/$documentId'
    | '/documents/duplicates'
    | '/documents/ocr-queue'
    | '/documents/search'
    | '/documents/sync-hms'
    | '/documents/upload'
    | '/help/diagnostics'
    | '/help/shortcuts'
    | '/integrations/hms'
    | '/integrations/llm'
    | '/integrations/vector-index'
    | '/medication-conflicts/$conflictId'
    | '/metrics/citations'
    | '/metrics/config'
    | '/metrics/feedback'
    | '/metrics/safe-refusal'
    | '/metrics/workflows'
    | '/patients/$patientId'
    | '/pharmacy/review-queue'
    | '/settings/ai'
    | '/settings/display'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/workspaces'
    | '/timeline/$eventId'
    | '/auth/sso/callback'
    | '/access-requests/'
    | '/audit/'
    | '/chat/'
    | '/dashboard/'
    | '/documents/'
    | '/metrics/'
    | '/patients/'
    | '/settings/'
    | '/timeline/'
    | '/access-requests/$requestId/review'
    | '/audit/$eventId/raw'
    | '/audit/traces/$traceId'
    | '/chat/patients/$patientId'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/retry'
    | '/documents/$documentId/review'
    | '/graph/path/$pathId'
    | '/graph/patients/$patientId'
    | '/integrations/hms/dlq'
    | '/integrations/traces/$traceId'
    | '/patients/$patientId/access-history'
    | '/patients/$patientId/documents'
    | '/patients/$patientId/labs'
    | '/patients/$patientId/medication-review'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/overview'
    | '/patients/$patientId/refresh'
    | '/patients/$patientId/timeline'
    | '/patients/$patientId/'
    | '/integrations/hms/jobs/$jobId'
    | '/integrations/hms/patients/$patientId/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-policy'
    | '/notifications'
    | '/screens'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/session-expired'
    | '/error/authentication-required'
    | '/error/conflict'
    | '/error/forbidden'
    | '/error/hms-unreachable'
    | '/error/insufficient-evidence'
    | '/error/llm-offline'
    | '/error/maintenance'
    | '/error/not-found'
    | '/error/ocr-failed'
    | '/error/offline'
    | '/error/patient-not-found'
    | '/error/rate-limit'
    | '/error/server'
    | '/error/timeout'
    | '/error'
    | '/access-requests/$requestId'
    | '/admin/abac'
    | '/admin/data-retention'
    | '/admin/roles'
    | '/audit/compliance-summary'
    | '/audit/denied'
    | '/audit/export'
    | '/chat/general'
    | '/chat/history'
    | '/chat/new'
    | '/chat/templates'
    | '/citations/$sourceId'
    | '/citations/compare'
    | '/dashboard/activity'
    | '/dashboard/customize'
    | '/documents/$documentId'
    | '/documents/duplicates'
    | '/documents/ocr-queue'
    | '/documents/search'
    | '/documents/sync-hms'
    | '/documents/upload'
    | '/help/diagnostics'
    | '/help/shortcuts'
    | '/integrations/hms'
    | '/integrations/llm'
    | '/integrations/vector-index'
    | '/medication-conflicts/$conflictId'
    | '/metrics/citations'
    | '/metrics/config'
    | '/metrics/feedback'
    | '/metrics/safe-refusal'
    | '/metrics/workflows'
    | '/pharmacy/review-queue'
    | '/settings/ai'
    | '/settings/display'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/workspaces'
    | '/timeline/$eventId'
    | '/auth/sso/callback'
    | '/access-requests'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/metrics'
    | '/patients'
    | '/settings'
    | '/timeline'
    | '/access-requests/$requestId/review'
    | '/audit/$eventId/raw'
    | '/audit/traces/$traceId'
    | '/chat/patients/$patientId'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/retry'
    | '/documents/$documentId/review'
    | '/graph/path/$pathId'
    | '/graph/patients/$patientId'
    | '/integrations/hms/dlq'
    | '/integrations/traces/$traceId'
    | '/patients/$patientId/access-history'
    | '/patients/$patientId/documents'
    | '/patients/$patientId/labs'
    | '/patients/$patientId/medication-review'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/overview'
    | '/patients/$patientId/refresh'
    | '/patients/$patientId/timeline'
    | '/patients/$patientId'
    | '/integrations/hms/jobs/$jobId'
    | '/integrations/hms/patients/$patientId/sync'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/access-policy'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/metrics'
    | '/_app/notifications'
    | '/_app/patients'
    | '/_app/screens'
    | '/_app/settings'
    | '/_app/timeline'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/session-expired'
    | '/error/authentication-required'
    | '/error/conflict'
    | '/error/forbidden'
    | '/error/hms-unreachable'
    | '/error/insufficient-evidence'
    | '/error/llm-offline'
    | '/error/maintenance'
    | '/error/not-found'
    | '/error/ocr-failed'
    | '/error/offline'
    | '/error/patient-not-found'
    | '/error/rate-limit'
    | '/error/server'
    | '/error/timeout'
    | '/error/'
    | '/_app/access-requests/$requestId'
    | '/_app/admin/abac'
    | '/_app/admin/data-retention'
    | '/_app/admin/roles'
    | '/_app/audit/compliance-summary'
    | '/_app/audit/denied'
    | '/_app/audit/export'
    | '/_app/chat/general'
    | '/_app/chat/history'
    | '/_app/chat/new'
    | '/_app/chat/templates'
    | '/_app/citations/$sourceId'
    | '/_app/citations/compare'
    | '/_app/dashboard/activity'
    | '/_app/dashboard/customize'
    | '/_app/documents/$documentId'
    | '/_app/documents/duplicates'
    | '/_app/documents/ocr-queue'
    | '/_app/documents/search'
    | '/_app/documents/sync-hms'
    | '/_app/documents/upload'
    | '/_app/help/diagnostics'
    | '/_app/help/shortcuts'
    | '/_app/integrations/hms'
    | '/_app/integrations/llm'
    | '/_app/integrations/vector-index'
    | '/_app/medication-conflicts/$conflictId'
    | '/_app/metrics/citations'
    | '/_app/metrics/config'
    | '/_app/metrics/feedback'
    | '/_app/metrics/safe-refusal'
    | '/_app/metrics/workflows'
    | '/_app/patients/$patientId'
    | '/_app/pharmacy/review-queue'
    | '/_app/settings/ai'
    | '/_app/settings/display'
    | '/_app/settings/profile'
    | '/_app/settings/security'
    | '/_app/settings/workspaces'
    | '/_app/timeline/$eventId'
    | '/auth/sso/callback'
    | '/_app/access-requests/'
    | '/_app/audit/'
    | '/_app/chat/'
    | '/_app/dashboard/'
    | '/_app/documents/'
    | '/_app/metrics/'
    | '/_app/patients/'
    | '/_app/settings/'
    | '/_app/timeline/'
    | '/_app/access-requests/$requestId/review'
    | '/_app/audit/$eventId/raw'
    | '/_app/audit/traces/$traceId'
    | '/_app/chat/patients/$patientId'
    | '/_app/documents/$documentId/edit'
    | '/_app/documents/$documentId/retry'
    | '/_app/documents/$documentId/review'
    | '/_app/graph/path/$pathId'
    | '/_app/graph/patients/$patientId'
    | '/_app/integrations/hms/dlq'
    | '/_app/integrations/traces/$traceId'
    | '/_app/patients/$patientId/access-history'
    | '/_app/patients/$patientId/documents'
    | '/_app/patients/$patientId/labs'
    | '/_app/patients/$patientId/medication-review'
    | '/_app/patients/$patientId/medications'
    | '/_app/patients/$patientId/overview'
    | '/_app/patients/$patientId/refresh'
    | '/_app/patients/$patientId/timeline'
    | '/_app/patients/$patientId/'
    | '/_app/integrations/hms/jobs/$jobId'
    | '/_app/integrations/hms/patients/$patientId/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthSessionExpiredRoute: typeof AuthSessionExpiredRoute
  ErrorAuthenticationRequiredRoute: typeof ErrorAuthenticationRequiredRoute
  ErrorConflictRoute: typeof ErrorConflictRoute
  ErrorForbiddenRoute: typeof ErrorForbiddenRoute
  ErrorHmsUnreachableRoute: typeof ErrorHmsUnreachableRoute
  ErrorInsufficientEvidenceRoute: typeof ErrorInsufficientEvidenceRoute
  ErrorLlmOfflineRoute: typeof ErrorLlmOfflineRoute
  ErrorMaintenanceRoute: typeof ErrorMaintenanceRoute
  ErrorNotFoundRoute: typeof ErrorNotFoundRoute
  ErrorOcrFailedRoute: typeof ErrorOcrFailedRoute
  ErrorOfflineRoute: typeof ErrorOfflineRoute
  ErrorPatientNotFoundRoute: typeof ErrorPatientNotFoundRoute
  ErrorRateLimitRoute: typeof ErrorRateLimitRoute
  ErrorServerRoute: typeof ErrorServerRoute
  ErrorTimeoutRoute: typeof ErrorTimeoutRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/timeout': {
      id: '/error/timeout'
      path: '/error/timeout'
      fullPath: '/error/timeout'
      preLoaderRoute: typeof ErrorTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/server': {
      id: '/error/server'
      path: '/error/server'
      fullPath: '/error/server'
      preLoaderRoute: typeof ErrorServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/rate-limit': {
      id: '/error/rate-limit'
      path: '/error/rate-limit'
      fullPath: '/error/rate-limit'
      preLoaderRoute: typeof ErrorRateLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/patient-not-found': {
      id: '/error/patient-not-found'
      path: '/error/patient-not-found'
      fullPath: '/error/patient-not-found'
      preLoaderRoute: typeof ErrorPatientNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/offline': {
      id: '/error/offline'
      path: '/error/offline'
      fullPath: '/error/offline'
      preLoaderRoute: typeof ErrorOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/ocr-failed': {
      id: '/error/ocr-failed'
      path: '/error/ocr-failed'
      fullPath: '/error/ocr-failed'
      preLoaderRoute: typeof ErrorOcrFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/not-found': {
      id: '/error/not-found'
      path: '/error/not-found'
      fullPath: '/error/not-found'
      preLoaderRoute: typeof ErrorNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/maintenance': {
      id: '/error/maintenance'
      path: '/error/maintenance'
      fullPath: '/error/maintenance'
      preLoaderRoute: typeof ErrorMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/llm-offline': {
      id: '/error/llm-offline'
      path: '/error/llm-offline'
      fullPath: '/error/llm-offline'
      preLoaderRoute: typeof ErrorLlmOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/insufficient-evidence': {
      id: '/error/insufficient-evidence'
      path: '/error/insufficient-evidence'
      fullPath: '/error/insufficient-evidence'
      preLoaderRoute: typeof ErrorInsufficientEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/hms-unreachable': {
      id: '/error/hms-unreachable'
      path: '/error/hms-unreachable'
      fullPath: '/error/hms-unreachable'
      preLoaderRoute: typeof ErrorHmsUnreachableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/forbidden': {
      id: '/error/forbidden'
      path: '/error/forbidden'
      fullPath: '/error/forbidden'
      preLoaderRoute: typeof ErrorForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/conflict': {
      id: '/error/conflict'
      path: '/error/conflict'
      fullPath: '/error/conflict'
      preLoaderRoute: typeof ErrorConflictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/authentication-required': {
      id: '/error/authentication-required'
      path: '/error/authentication-required'
      fullPath: '/error/authentication-required'
      preLoaderRoute: typeof ErrorAuthenticationRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/session-expired': {
      id: '/auth/session-expired'
      path: '/auth/session-expired'
      fullPath: '/auth/session-expired'
      preLoaderRoute: typeof AuthSessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screens': {
      id: '/_app/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof AppScreensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access-policy': {
      id: '/_app/access-policy'
      path: '/access-policy'
      fullPath: '/access-policy'
      preLoaderRoute: typeof AppAccessPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline/': {
      id: '/_app/timeline/'
      path: '/'
      fullPath: '/timeline/'
      preLoaderRoute: typeof AppTimelineIndexRouteImport
      parentRoute: typeof AppTimelineRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppPatientsRoute
    }
    '/_app/metrics/': {
      id: '/_app/metrics/'
      path: '/'
      fullPath: '/metrics/'
      preLoaderRoute: typeof AppMetricsIndexRouteImport
      parentRoute: typeof AppMetricsRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/access-requests/': {
      id: '/_app/access-requests/'
      path: '/access-requests'
      fullPath: '/access-requests/'
      preLoaderRoute: typeof AppAccessRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sso/callback': {
      id: '/auth/sso/callback'
      path: '/auth/sso/callback'
      fullPath: '/auth/sso/callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timeline/$eventId': {
      id: '/_app/timeline/$eventId'
      path: '/$eventId'
      fullPath: '/timeline/$eventId'
      preLoaderRoute: typeof AppTimelineEventIdRouteImport
      parentRoute: typeof AppTimelineRoute
    }
    '/_app/settings/workspaces': {
      id: '/_app/settings/workspaces'
      path: '/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof AppSettingsWorkspacesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/display': {
      id: '/_app/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AppSettingsDisplayRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/pharmacy/review-queue': {
      id: '/_app/pharmacy/review-queue'
      path: '/pharmacy/review-queue'
      fullPath: '/pharmacy/review-queue'
      preLoaderRoute: typeof AppPharmacyReviewQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId': {
      id: '/_app/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppPatientsRoute
    }
    '/_app/metrics/workflows': {
      id: '/_app/metrics/workflows'
      path: '/workflows'
      fullPath: '/metrics/workflows'
      preLoaderRoute: typeof AppMetricsWorkflowsRouteImport
      parentRoute: typeof AppMetricsRoute
    }
    '/_app/metrics/safe-refusal': {
      id: '/_app/metrics/safe-refusal'
      path: '/safe-refusal'
      fullPath: '/metrics/safe-refusal'
      preLoaderRoute: typeof AppMetricsSafeRefusalRouteImport
      parentRoute: typeof AppMetricsRoute
    }
    '/_app/metrics/feedback': {
      id: '/_app/metrics/feedback'
      path: '/feedback'
      fullPath: '/metrics/feedback'
      preLoaderRoute: typeof AppMetricsFeedbackRouteImport
      parentRoute: typeof AppMetricsRoute
    }
    '/_app/metrics/config': {
      id: '/_app/metrics/config'
      path: '/config'
      fullPath: '/metrics/config'
      preLoaderRoute: typeof AppMetricsConfigRouteImport
      parentRoute: typeof AppMetricsRoute
    }
    '/_app/metrics/citations': {
      id: '/_app/metrics/citations'
      path: '/citations'
      fullPath: '/metrics/citations'
      preLoaderRoute: typeof AppMetricsCitationsRouteImport
      parentRoute: typeof AppMetricsRoute
    }
    '/_app/medication-conflicts/$conflictId': {
      id: '/_app/medication-conflicts/$conflictId'
      path: '/medication-conflicts/$conflictId'
      fullPath: '/medication-conflicts/$conflictId'
      preLoaderRoute: typeof AppMedicationConflictsConflictIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/vector-index': {
      id: '/_app/integrations/vector-index'
      path: '/integrations/vector-index'
      fullPath: '/integrations/vector-index'
      preLoaderRoute: typeof AppIntegrationsVectorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/llm': {
      id: '/_app/integrations/llm'
      path: '/integrations/llm'
      fullPath: '/integrations/llm'
      preLoaderRoute: typeof AppIntegrationsLlmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/hms': {
      id: '/_app/integrations/hms'
      path: '/integrations/hms'
      fullPath: '/integrations/hms'
      preLoaderRoute: typeof AppIntegrationsHmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/shortcuts': {
      id: '/_app/help/shortcuts'
      path: '/help/shortcuts'
      fullPath: '/help/shortcuts'
      preLoaderRoute: typeof AppHelpShortcutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/diagnostics': {
      id: '/_app/help/diagnostics'
      path: '/help/diagnostics'
      fullPath: '/help/diagnostics'
      preLoaderRoute: typeof AppHelpDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/upload': {
      id: '/_app/documents/upload'
      path: '/upload'
      fullPath: '/documents/upload'
      preLoaderRoute: typeof AppDocumentsUploadRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/documents/sync-hms': {
      id: '/_app/documents/sync-hms'
      path: '/sync-hms'
      fullPath: '/documents/sync-hms'
      preLoaderRoute: typeof AppDocumentsSyncHmsRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/documents/search': {
      id: '/_app/documents/search'
      path: '/search'
      fullPath: '/documents/search'
      preLoaderRoute: typeof AppDocumentsSearchRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/documents/ocr-queue': {
      id: '/_app/documents/ocr-queue'
      path: '/ocr-queue'
      fullPath: '/documents/ocr-queue'
      preLoaderRoute: typeof AppDocumentsOcrQueueRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/documents/duplicates': {
      id: '/_app/documents/duplicates'
      path: '/duplicates'
      fullPath: '/documents/duplicates'
      preLoaderRoute: typeof AppDocumentsDuplicatesRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/documents/$documentId': {
      id: '/_app/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/dashboard/customize': {
      id: '/_app/dashboard/customize'
      path: '/customize'
      fullPath: '/dashboard/customize'
      preLoaderRoute: typeof AppDashboardCustomizeRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/activity': {
      id: '/_app/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof AppDashboardActivityRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/citations/compare': {
      id: '/_app/citations/compare'
      path: '/citations/compare'
      fullPath: '/citations/compare'
      preLoaderRoute: typeof AppCitationsCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/citations/$sourceId': {
      id: '/_app/citations/$sourceId'
      path: '/citations/$sourceId'
      fullPath: '/citations/$sourceId'
      preLoaderRoute: typeof AppCitationsSourceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/templates': {
      id: '/_app/chat/templates'
      path: '/chat/templates'
      fullPath: '/chat/templates'
      preLoaderRoute: typeof AppChatTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/new': {
      id: '/_app/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof AppChatNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/history': {
      id: '/_app/chat/history'
      path: '/chat/history'
      fullPath: '/chat/history'
      preLoaderRoute: typeof AppChatHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/general': {
      id: '/_app/chat/general'
      path: '/chat/general'
      fullPath: '/chat/general'
      preLoaderRoute: typeof AppChatGeneralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/export': {
      id: '/_app/audit/export'
      path: '/export'
      fullPath: '/audit/export'
      preLoaderRoute: typeof AppAuditExportRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/audit/denied': {
      id: '/_app/audit/denied'
      path: '/denied'
      fullPath: '/audit/denied'
      preLoaderRoute: typeof AppAuditDeniedRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/audit/compliance-summary': {
      id: '/_app/audit/compliance-summary'
      path: '/compliance-summary'
      fullPath: '/audit/compliance-summary'
      preLoaderRoute: typeof AppAuditComplianceSummaryRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/data-retention': {
      id: '/_app/admin/data-retention'
      path: '/admin/data-retention'
      fullPath: '/admin/data-retention'
      preLoaderRoute: typeof AppAdminDataRetentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/abac': {
      id: '/_app/admin/abac'
      path: '/admin/abac'
      fullPath: '/admin/abac'
      preLoaderRoute: typeof AppAdminAbacRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access-requests/$requestId': {
      id: '/_app/access-requests/$requestId'
      path: '/access-requests/$requestId'
      fullPath: '/access-requests/$requestId'
      preLoaderRoute: typeof AppAccessRequestsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/': {
      id: '/_app/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AppPatientsPatientIdIndexRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/patients/$patientId/timeline': {
      id: '/_app/patients/$patientId/timeline'
      path: '/timeline'
      fullPath: '/patients/$patientId/timeline'
      preLoaderRoute: typeof AppPatientsPatientIdTimelineRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/patients/$patientId/refresh': {
      id: '/_app/patients/$patientId/refresh'
      path: '/refresh'
      fullPath: '/patients/$patientId/refresh'
      preLoaderRoute: typeof AppPatientsPatientIdRefreshRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/patients/$patientId/overview': {
      id: '/_app/patients/$patientId/overview'
      path: '/overview'
      fullPath: '/patients/$patientId/overview'
      preLoaderRoute: typeof AppPatientsPatientIdOverviewRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/patients/$patientId/medications': {
      id: '/_app/patients/$patientId/medications'
      path: '/medications'
      fullPath: '/patients/$patientId/medications'
      preLoaderRoute: typeof AppPatientsPatientIdMedicationsRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/patients/$patientId/medication-review': {
      id: '/_app/patients/$patientId/medication-review'
      path: '/medication-review'
      fullPath: '/patients/$patientId/medication-review'
      preLoaderRoute: typeof AppPatientsPatientIdMedicationReviewRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/patients/$patientId/labs': {
      id: '/_app/patients/$patientId/labs'
      path: '/labs'
      fullPath: '/patients/$patientId/labs'
      preLoaderRoute: typeof AppPatientsPatientIdLabsRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/patients/$patientId/documents': {
      id: '/_app/patients/$patientId/documents'
      path: '/documents'
      fullPath: '/patients/$patientId/documents'
      preLoaderRoute: typeof AppPatientsPatientIdDocumentsRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/patients/$patientId/access-history': {
      id: '/_app/patients/$patientId/access-history'
      path: '/access-history'
      fullPath: '/patients/$patientId/access-history'
      preLoaderRoute: typeof AppPatientsPatientIdAccessHistoryRouteImport
      parentRoute: typeof AppPatientsPatientIdRoute
    }
    '/_app/integrations/traces/$traceId': {
      id: '/_app/integrations/traces/$traceId'
      path: '/integrations/traces/$traceId'
      fullPath: '/integrations/traces/$traceId'
      preLoaderRoute: typeof AppIntegrationsTracesTraceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/hms/dlq': {
      id: '/_app/integrations/hms/dlq'
      path: '/dlq'
      fullPath: '/integrations/hms/dlq'
      preLoaderRoute: typeof AppIntegrationsHmsDlqRouteImport
      parentRoute: typeof AppIntegrationsHmsRoute
    }
    '/_app/graph/patients/$patientId': {
      id: '/_app/graph/patients/$patientId'
      path: '/graph/patients/$patientId'
      fullPath: '/graph/patients/$patientId'
      preLoaderRoute: typeof AppGraphPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph/path/$pathId': {
      id: '/_app/graph/path/$pathId'
      path: '/graph/path/$pathId'
      fullPath: '/graph/path/$pathId'
      preLoaderRoute: typeof AppGraphPathPathIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/$documentId/review': {
      id: '/_app/documents/$documentId/review'
      path: '/review'
      fullPath: '/documents/$documentId/review'
      preLoaderRoute: typeof AppDocumentsDocumentIdReviewRouteImport
      parentRoute: typeof AppDocumentsDocumentIdRoute
    }
    '/_app/documents/$documentId/retry': {
      id: '/_app/documents/$documentId/retry'
      path: '/retry'
      fullPath: '/documents/$documentId/retry'
      preLoaderRoute: typeof AppDocumentsDocumentIdRetryRouteImport
      parentRoute: typeof AppDocumentsDocumentIdRoute
    }
    '/_app/documents/$documentId/edit': {
      id: '/_app/documents/$documentId/edit'
      path: '/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof AppDocumentsDocumentIdEditRouteImport
      parentRoute: typeof AppDocumentsDocumentIdRoute
    }
    '/_app/chat/patients/$patientId': {
      id: '/_app/chat/patients/$patientId'
      path: '/chat/patients/$patientId'
      fullPath: '/chat/patients/$patientId'
      preLoaderRoute: typeof AppChatPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/traces/$traceId': {
      id: '/_app/audit/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/audit/traces/$traceId'
      preLoaderRoute: typeof AppAuditTracesTraceIdRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/audit/$eventId/raw': {
      id: '/_app/audit/$eventId/raw'
      path: '/$eventId/raw'
      fullPath: '/audit/$eventId/raw'
      preLoaderRoute: typeof AppAuditEventIdRawRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/access-requests/$requestId/review': {
      id: '/_app/access-requests/$requestId/review'
      path: '/review'
      fullPath: '/access-requests/$requestId/review'
      preLoaderRoute: typeof AppAccessRequestsRequestIdReviewRouteImport
      parentRoute: typeof AppAccessRequestsRequestIdRoute
    }
    '/_app/integrations/hms/jobs/$jobId': {
      id: '/_app/integrations/hms/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/integrations/hms/jobs/$jobId'
      preLoaderRoute: typeof AppIntegrationsHmsJobsJobIdRouteImport
      parentRoute: typeof AppIntegrationsHmsRoute
    }
    '/_app/integrations/hms/patients/$patientId/sync': {
      id: '/_app/integrations/hms/patients/$patientId/sync'
      path: '/patients/$patientId/sync'
      fullPath: '/integrations/hms/patients/$patientId/sync'
      preLoaderRoute: typeof AppIntegrationsHmsPatientsPatientIdSyncRouteImport
      parentRoute: typeof AppIntegrationsHmsRoute
    }
  }
}

interface AppAuditRouteChildren {
  AppAuditComplianceSummaryRoute: typeof AppAuditComplianceSummaryRoute
  AppAuditDeniedRoute: typeof AppAuditDeniedRoute
  AppAuditExportRoute: typeof AppAuditExportRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppAuditEventIdRawRoute: typeof AppAuditEventIdRawRoute
  AppAuditTracesTraceIdRoute: typeof AppAuditTracesTraceIdRoute
}

const AppAuditRouteChildren: AppAuditRouteChildren = {
  AppAuditComplianceSummaryRoute: AppAuditComplianceSummaryRoute,
  AppAuditDeniedRoute: AppAuditDeniedRoute,
  AppAuditExportRoute: AppAuditExportRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppAuditEventIdRawRoute: AppAuditEventIdRawRoute,
  AppAuditTracesTraceIdRoute: AppAuditTracesTraceIdRoute,
}

const AppAuditRouteWithChildren = AppAuditRoute._addFileChildren(
  AppAuditRouteChildren,
)

interface AppDashboardRouteChildren {
  AppDashboardActivityRoute: typeof AppDashboardActivityRoute
  AppDashboardCustomizeRoute: typeof AppDashboardCustomizeRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardActivityRoute: AppDashboardActivityRoute,
  AppDashboardCustomizeRoute: AppDashboardCustomizeRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppDocumentsDocumentIdRouteChildren {
  AppDocumentsDocumentIdEditRoute: typeof AppDocumentsDocumentIdEditRoute
  AppDocumentsDocumentIdRetryRoute: typeof AppDocumentsDocumentIdRetryRoute
  AppDocumentsDocumentIdReviewRoute: typeof AppDocumentsDocumentIdReviewRoute
}

const AppDocumentsDocumentIdRouteChildren: AppDocumentsDocumentIdRouteChildren =
  {
    AppDocumentsDocumentIdEditRoute: AppDocumentsDocumentIdEditRoute,
    AppDocumentsDocumentIdRetryRoute: AppDocumentsDocumentIdRetryRoute,
    AppDocumentsDocumentIdReviewRoute: AppDocumentsDocumentIdReviewRoute,
  }

const AppDocumentsDocumentIdRouteWithChildren =
  AppDocumentsDocumentIdRoute._addFileChildren(
    AppDocumentsDocumentIdRouteChildren,
  )

interface AppDocumentsRouteChildren {
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRouteWithChildren
  AppDocumentsDuplicatesRoute: typeof AppDocumentsDuplicatesRoute
  AppDocumentsOcrQueueRoute: typeof AppDocumentsOcrQueueRoute
  AppDocumentsSearchRoute: typeof AppDocumentsSearchRoute
  AppDocumentsSyncHmsRoute: typeof AppDocumentsSyncHmsRoute
  AppDocumentsUploadRoute: typeof AppDocumentsUploadRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRouteWithChildren,
  AppDocumentsDuplicatesRoute: AppDocumentsDuplicatesRoute,
  AppDocumentsOcrQueueRoute: AppDocumentsOcrQueueRoute,
  AppDocumentsSearchRoute: AppDocumentsSearchRoute,
  AppDocumentsSyncHmsRoute: AppDocumentsSyncHmsRoute,
  AppDocumentsUploadRoute: AppDocumentsUploadRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppMetricsRouteChildren {
  AppMetricsCitationsRoute: typeof AppMetricsCitationsRoute
  AppMetricsConfigRoute: typeof AppMetricsConfigRoute
  AppMetricsFeedbackRoute: typeof AppMetricsFeedbackRoute
  AppMetricsSafeRefusalRoute: typeof AppMetricsSafeRefusalRoute
  AppMetricsWorkflowsRoute: typeof AppMetricsWorkflowsRoute
  AppMetricsIndexRoute: typeof AppMetricsIndexRoute
}

const AppMetricsRouteChildren: AppMetricsRouteChildren = {
  AppMetricsCitationsRoute: AppMetricsCitationsRoute,
  AppMetricsConfigRoute: AppMetricsConfigRoute,
  AppMetricsFeedbackRoute: AppMetricsFeedbackRoute,
  AppMetricsSafeRefusalRoute: AppMetricsSafeRefusalRoute,
  AppMetricsWorkflowsRoute: AppMetricsWorkflowsRoute,
  AppMetricsIndexRoute: AppMetricsIndexRoute,
}

const AppMetricsRouteWithChildren = AppMetricsRoute._addFileChildren(
  AppMetricsRouteChildren,
)

interface AppPatientsPatientIdRouteChildren {
  AppPatientsPatientIdAccessHistoryRoute: typeof AppPatientsPatientIdAccessHistoryRoute
  AppPatientsPatientIdDocumentsRoute: typeof AppPatientsPatientIdDocumentsRoute
  AppPatientsPatientIdLabsRoute: typeof AppPatientsPatientIdLabsRoute
  AppPatientsPatientIdMedicationReviewRoute: typeof AppPatientsPatientIdMedicationReviewRoute
  AppPatientsPatientIdMedicationsRoute: typeof AppPatientsPatientIdMedicationsRoute
  AppPatientsPatientIdOverviewRoute: typeof AppPatientsPatientIdOverviewRoute
  AppPatientsPatientIdRefreshRoute: typeof AppPatientsPatientIdRefreshRoute
  AppPatientsPatientIdTimelineRoute: typeof AppPatientsPatientIdTimelineRoute
  AppPatientsPatientIdIndexRoute: typeof AppPatientsPatientIdIndexRoute
}

const AppPatientsPatientIdRouteChildren: AppPatientsPatientIdRouteChildren = {
  AppPatientsPatientIdAccessHistoryRoute:
    AppPatientsPatientIdAccessHistoryRoute,
  AppPatientsPatientIdDocumentsRoute: AppPatientsPatientIdDocumentsRoute,
  AppPatientsPatientIdLabsRoute: AppPatientsPatientIdLabsRoute,
  AppPatientsPatientIdMedicationReviewRoute:
    AppPatientsPatientIdMedicationReviewRoute,
  AppPatientsPatientIdMedicationsRoute: AppPatientsPatientIdMedicationsRoute,
  AppPatientsPatientIdOverviewRoute: AppPatientsPatientIdOverviewRoute,
  AppPatientsPatientIdRefreshRoute: AppPatientsPatientIdRefreshRoute,
  AppPatientsPatientIdTimelineRoute: AppPatientsPatientIdTimelineRoute,
  AppPatientsPatientIdIndexRoute: AppPatientsPatientIdIndexRoute,
}

const AppPatientsPatientIdRouteWithChildren =
  AppPatientsPatientIdRoute._addFileChildren(AppPatientsPatientIdRouteChildren)

interface AppPatientsRouteChildren {
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRouteWithChildren
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppPatientsRouteChildren: AppPatientsRouteChildren = {
  AppPatientsPatientIdRoute: AppPatientsPatientIdRouteWithChildren,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppPatientsRouteWithChildren = AppPatientsRoute._addFileChildren(
  AppPatientsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsDisplayRoute: typeof AppSettingsDisplayRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsWorkspacesRoute: typeof AppSettingsWorkspacesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsDisplayRoute: AppSettingsDisplayRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsWorkspacesRoute: AppSettingsWorkspacesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTimelineRouteChildren {
  AppTimelineEventIdRoute: typeof AppTimelineEventIdRoute
  AppTimelineIndexRoute: typeof AppTimelineIndexRoute
}

const AppTimelineRouteChildren: AppTimelineRouteChildren = {
  AppTimelineEventIdRoute: AppTimelineEventIdRoute,
  AppTimelineIndexRoute: AppTimelineIndexRoute,
}

const AppTimelineRouteWithChildren = AppTimelineRoute._addFileChildren(
  AppTimelineRouteChildren,
)

interface AppAccessRequestsRequestIdRouteChildren {
  AppAccessRequestsRequestIdReviewRoute: typeof AppAccessRequestsRequestIdReviewRoute
}

const AppAccessRequestsRequestIdRouteChildren: AppAccessRequestsRequestIdRouteChildren =
  {
    AppAccessRequestsRequestIdReviewRoute:
      AppAccessRequestsRequestIdReviewRoute,
  }

const AppAccessRequestsRequestIdRouteWithChildren =
  AppAccessRequestsRequestIdRoute._addFileChildren(
    AppAccessRequestsRequestIdRouteChildren,
  )

interface AppIntegrationsHmsRouteChildren {
  AppIntegrationsHmsDlqRoute: typeof AppIntegrationsHmsDlqRoute
  AppIntegrationsHmsJobsJobIdRoute: typeof AppIntegrationsHmsJobsJobIdRoute
  AppIntegrationsHmsPatientsPatientIdSyncRoute: typeof AppIntegrationsHmsPatientsPatientIdSyncRoute
}

const AppIntegrationsHmsRouteChildren: AppIntegrationsHmsRouteChildren = {
  AppIntegrationsHmsDlqRoute: AppIntegrationsHmsDlqRoute,
  AppIntegrationsHmsJobsJobIdRoute: AppIntegrationsHmsJobsJobIdRoute,
  AppIntegrationsHmsPatientsPatientIdSyncRoute:
    AppIntegrationsHmsPatientsPatientIdSyncRoute,
}

const AppIntegrationsHmsRouteWithChildren =
  AppIntegrationsHmsRoute._addFileChildren(AppIntegrationsHmsRouteChildren)

interface AppRouteChildren {
  AppAccessPolicyRoute: typeof AppAccessPolicyRoute
  AppAuditRoute: typeof AppAuditRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppMetricsRoute: typeof AppMetricsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatientsRoute: typeof AppPatientsRouteWithChildren
  AppScreensRoute: typeof AppScreensRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTimelineRoute: typeof AppTimelineRouteWithChildren
  AppAccessRequestsRequestIdRoute: typeof AppAccessRequestsRequestIdRouteWithChildren
  AppAdminAbacRoute: typeof AppAdminAbacRoute
  AppAdminDataRetentionRoute: typeof AppAdminDataRetentionRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppChatGeneralRoute: typeof AppChatGeneralRoute
  AppChatHistoryRoute: typeof AppChatHistoryRoute
  AppChatNewRoute: typeof AppChatNewRoute
  AppChatTemplatesRoute: typeof AppChatTemplatesRoute
  AppCitationsSourceIdRoute: typeof AppCitationsSourceIdRoute
  AppCitationsCompareRoute: typeof AppCitationsCompareRoute
  AppHelpDiagnosticsRoute: typeof AppHelpDiagnosticsRoute
  AppHelpShortcutsRoute: typeof AppHelpShortcutsRoute
  AppIntegrationsHmsRoute: typeof AppIntegrationsHmsRouteWithChildren
  AppIntegrationsLlmRoute: typeof AppIntegrationsLlmRoute
  AppIntegrationsVectorIndexRoute: typeof AppIntegrationsVectorIndexRoute
  AppMedicationConflictsConflictIdRoute: typeof AppMedicationConflictsConflictIdRoute
  AppPharmacyReviewQueueRoute: typeof AppPharmacyReviewQueueRoute
  AppAccessRequestsIndexRoute: typeof AppAccessRequestsIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppChatPatientsPatientIdRoute: typeof AppChatPatientsPatientIdRoute
  AppGraphPathPathIdRoute: typeof AppGraphPathPathIdRoute
  AppGraphPatientsPatientIdRoute: typeof AppGraphPatientsPatientIdRoute
  AppIntegrationsTracesTraceIdRoute: typeof AppIntegrationsTracesTraceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessPolicyRoute: AppAccessPolicyRoute,
  AppAuditRoute: AppAuditRouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppMetricsRoute: AppMetricsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatientsRoute: AppPatientsRouteWithChildren,
  AppScreensRoute: AppScreensRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTimelineRoute: AppTimelineRouteWithChildren,
  AppAccessRequestsRequestIdRoute: AppAccessRequestsRequestIdRouteWithChildren,
  AppAdminAbacRoute: AppAdminAbacRoute,
  AppAdminDataRetentionRoute: AppAdminDataRetentionRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppChatGeneralRoute: AppChatGeneralRoute,
  AppChatHistoryRoute: AppChatHistoryRoute,
  AppChatNewRoute: AppChatNewRoute,
  AppChatTemplatesRoute: AppChatTemplatesRoute,
  AppCitationsSourceIdRoute: AppCitationsSourceIdRoute,
  AppCitationsCompareRoute: AppCitationsCompareRoute,
  AppHelpDiagnosticsRoute: AppHelpDiagnosticsRoute,
  AppHelpShortcutsRoute: AppHelpShortcutsRoute,
  AppIntegrationsHmsRoute: AppIntegrationsHmsRouteWithChildren,
  AppIntegrationsLlmRoute: AppIntegrationsLlmRoute,
  AppIntegrationsVectorIndexRoute: AppIntegrationsVectorIndexRoute,
  AppMedicationConflictsConflictIdRoute: AppMedicationConflictsConflictIdRoute,
  AppPharmacyReviewQueueRoute: AppPharmacyReviewQueueRoute,
  AppAccessRequestsIndexRoute: AppAccessRequestsIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppChatPatientsPatientIdRoute: AppChatPatientsPatientIdRoute,
  AppGraphPathPathIdRoute: AppGraphPathPathIdRoute,
  AppGraphPatientsPatientIdRoute: AppGraphPatientsPatientIdRoute,
  AppIntegrationsTracesTraceIdRoute: AppIntegrationsTracesTraceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthSessionExpiredRoute: AuthSessionExpiredRoute,
  ErrorAuthenticationRequiredRoute: ErrorAuthenticationRequiredRoute,
  ErrorConflictRoute: ErrorConflictRoute,
  ErrorForbiddenRoute: ErrorForbiddenRoute,
  ErrorHmsUnreachableRoute: ErrorHmsUnreachableRoute,
  ErrorInsufficientEvidenceRoute: ErrorInsufficientEvidenceRoute,
  ErrorLlmOfflineRoute: ErrorLlmOfflineRoute,
  ErrorMaintenanceRoute: ErrorMaintenanceRoute,
  ErrorNotFoundRoute: ErrorNotFoundRoute,
  ErrorOcrFailedRoute: ErrorOcrFailedRoute,
  ErrorOfflineRoute: ErrorOfflineRoute,
  ErrorPatientNotFoundRoute: ErrorPatientNotFoundRoute,
  ErrorRateLimitRoute: ErrorRateLimitRoute,
  ErrorServerRoute: ErrorServerRoute,
  ErrorTimeoutRoute: ErrorTimeoutRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
