"""make_document_patient_id_nullable

Revision ID: 60e7683f03bd
Revises: 209270610b31
Create Date: 2026-06-21 12:57:20.861384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import hospital_ai


# revision identifiers, used by Alembic.
revision: str = '60e7683f03bd'
down_revision: Union[str, None] = '209270610b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_queries', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_ai_queries_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_queries_user_id'), ['user_id'], unique=False)

        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=hospital_ai.db.models.InetAddress(length=64),
               existing_nullable=True,
               postgresql_using='ip_address::inet')
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_created'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_patient_created'))
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_document_chunks_patient_document'))
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_patient_id'), ['patient_id'], unique=False)
        batch_op.drop_column('search_vector')

    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_documents_patient_status'))
        batch_op.create_index(batch_op.f('ix_documents_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('patient_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_permissions_user_patient_scope'))
        batch_op.create_index(batch_op.f('ix_patient_permissions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_permissions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('retrieved_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieved_evidence_ai_query_id'), ['ai_query_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieved_evidence_chunk_id'), ['chunk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrieved_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieved_evidence_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_retrieved_evidence_ai_query_id'))

    with op.batch_alter_table('patient_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_patient_permissions_patient_id'))
        batch_op.create_index(batch_op.f('ix_patient_permissions_user_patient_scope'), ['user_id', 'patient_id', 'scope'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_patient_id'))
        batch_op.create_index(batch_op.f('ix_documents_patient_status'), ['patient_id', 'status'], unique=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_document_chunks_patient_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_page_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.create_index(batch_op.f('ix_document_chunks_patient_document'), ['patient_id', 'document_id'], unique=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.create_index(batch_op.f('ix_audit_logs_patient_created'), ['patient_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_created'), ['actor_user_id', 'created_at'], unique=False)
        batch_op.alter_column('ip_address',
               existing_type=hospital_ai.db.models.InetAddress(length=64),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True,
               postgresql_using='ip_address::varchar')

    with op.batch_alter_table('ai_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_queries_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_queries_patient_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
