"""Add ClinicalAlert model

Revision ID: 68666b884f62
Revises: 209270610b31
Create Date: 2026-07-12 02:05:54.829275

"""
from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa

import hospital_ai.db.models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68666b884f62'
down_revision: Union[str, None] = 'ae930a5b7521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity in ('low','medium','high')", name='ck_clinical_alerts_severity'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_alerts_patient_id'), ['patient_id'], unique=False)


def downgrade() -> None:
    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_alerts_patient_id'))

    op.drop_table('clinical_alerts')
    # ### end Alembic commands ###
