"""Add ClinicalAlert model

Revision ID: 68666b884f62
Revises: 209270610b31
Create Date: 2026-07-12 02:05:54.829275

"""
from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa

import hospital_ai.db.models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68666b884f62'
down_revision: Union[str, None] = '209270610b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity in ('low','medium','high')", name='ck_clinical_alerts_severity'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_alerts_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('graph_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_relations_relation_type'))
        batch_op.drop_index(batch_op.f('ix_graph_relations_source_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_graph_relations_source_entity_id'))
        batch_op.drop_index(batch_op.f('ix_graph_relations_target_entity_id'))

    op.drop_table('graph_relations')
    with op.batch_alter_table('metric_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_events_query_id'))
        batch_op.drop_index(batch_op.f('ix_metric_events_user_id'))

    op.drop_table('metric_events')
    with op.batch_alter_table('graph_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_entities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_graph_entities_name'))
        batch_op.drop_index(batch_op.f('ix_graph_entities_source_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_graph_entities_source_document_id'))

    op.drop_table('graph_entities')
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_query_id'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_user_id'))

    op.drop_table('user_feedback')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table('system_settings',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('value_json', sa.TEXT(), nullable=False),
    sa.Column('updated_by_user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=1)

    op.create_table('user_feedback',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('query_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating >= -1 AND rating <= 1', name=op.f('ck_user_feedback_rating')),
    sa.ForeignKeyConstraint(['query_id'], ['ai_queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_query_id'), ['query_id'], unique=False)

    op.create_table('graph_entities',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('source_chunk_id', sa.CHAR(length=32), nullable=False),
    sa.Column('source_document_id', sa.CHAR(length=32), nullable=False),
    sa.Column('confidence', sa.FLOAT(), server_default=sa.text("'1.0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_entities_source_document_id'), ['source_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_entities_source_chunk_id'), ['source_chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_entities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_entities_entity_type'), ['entity_type'], unique=False)

    op.create_table('metric_events',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('query_id', sa.CHAR(length=32), nullable=True),
    sa.Column('user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('task_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('baseline_manual_time_sec', sa.INTEGER(), nullable=True),
    sa.Column('actual_ai_time_sec', sa.INTEGER(), nullable=True),
    sa.Column('estimated_time_saved_sec', sa.INTEGER(), nullable=True),
    sa.Column('estimated_cost_saved', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('documents_retrieved', sa.INTEGER(), nullable=True),
    sa.Column('citations_count', sa.INTEGER(), nullable=True),
    sa.Column('query_latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('retrieval_latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('generation_latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('shared_thread_id', sa.CHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['ai_queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_events_query_id'), ['query_id'], unique=False)

    op.create_table('graph_relations',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('source_entity_id', sa.CHAR(length=32), nullable=False),
    sa.Column('target_entity_id', sa.CHAR(length=32), nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('weight', sa.FLOAT(), server_default=sa.text("'1.0'"), nullable=False),
    sa.Column('source_chunk_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['graph_entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['graph_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_relations_target_entity_id'), ['target_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_relations_source_entity_id'), ['source_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_relations_source_chunk_id'), ['source_chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_relations_relation_type'), ['relation_type'], unique=False)

    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_alerts_patient_id'))

    op.drop_table('clinical_alerts')
    # ### end Alembic commands ###
