"""fix: cdi v2 final model alignments

Revision ID: 704142b14459
Revises: cdi_v2_0003
Create Date: 2026-08-05 22:10:07.409140

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "704142b14459"
down_revision: Union[str, None] = "cdi_v2_0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("legacy_graph_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_relations_relation_type"))
        batch_op.drop_index(batch_op.f("ix_graph_relations_source_chunk_id"))
        batch_op.drop_index(batch_op.f("ix_graph_relations_source_entity_id"))
        batch_op.drop_index(batch_op.f("ix_graph_relations_target_entity_id"))
        batch_op.create_index(batch_op.f("ix_legacy_graph_relations_relation_type"), ["relation_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_legacy_graph_relations_source_chunk_id"), ["source_chunk_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_legacy_graph_relations_source_entity_id"), ["source_entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_legacy_graph_relations_target_entity_id"), ["target_entity_id"], unique=False
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.DateTime(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.DateTime(),
            existing_nullable=False,
        )

    with op.batch_alter_table("ai_queries", schema=None) as batch_op:
        batch_op.drop_column("last_emitted_sequence")
        batch_op.drop_column("validation_mode")

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_document_chunk_index"), type_="unique")
        batch_op.create_unique_constraint("uq_document_chunk_index", ["document_id", "generation_id", "chunk_index"])

    with op.batch_alter_table("document_uploads", schema=None) as batch_op:
        batch_op.drop_column("quarantine_result")

    with op.batch_alter_table("legacy_graph_entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_entities_entity_type"))
        batch_op.drop_index(batch_op.f("ix_graph_entities_name"))
        batch_op.drop_index(batch_op.f("ix_graph_entities_source_chunk_id"))
        batch_op.drop_index(batch_op.f("ix_graph_entities_source_document_id"))
        batch_op.create_index(batch_op.f("ix_legacy_graph_entities_source_chunk_id"), ["source_chunk_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_legacy_graph_entities_source_document_id"), ["source_document_id"], unique=False
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("legacy_graph_entities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_legacy_graph_entities_source_document_id"))
        batch_op.drop_index(batch_op.f("ix_legacy_graph_entities_source_chunk_id"))
        batch_op.create_index(batch_op.f("ix_graph_entities_source_document_id"), ["source_document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_entities_source_chunk_id"), ["source_chunk_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_entities_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_entities_entity_type"), ["entity_type"], unique=False)

    with op.batch_alter_table("legacy_graph_relations", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )

    with op.batch_alter_table("legacy_graph_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_legacy_graph_relations_relation_type"))
        batch_op.drop_index(batch_op.f("ix_legacy_graph_relations_source_chunk_id"))
        batch_op.drop_index(batch_op.f("ix_legacy_graph_relations_source_entity_id"))
        batch_op.drop_index(batch_op.f("ix_legacy_graph_relations_target_entity_id"))
        batch_op.create_index(batch_op.f("ix_graph_relations_relation_type"), ["relation_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_relations_source_chunk_id"), ["source_chunk_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_relations_source_entity_id"), ["source_entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_relations_target_entity_id"), ["target_entity_id"], unique=False)

    with op.batch_alter_table("document_uploads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quarantine_result", sa.TEXT(), nullable=True))

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_document_chunk_index", type_="unique")
        batch_op.create_unique_constraint(batch_op.f("uq_document_chunk_index"), ["document_id", "chunk_index"])

    with op.batch_alter_table("ai_queries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("validation_mode", sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("last_emitted_sequence", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True)
        )

    # ### end Alembic commands ###
