"""Add clinical document intelligence models

Revision ID: 8d6cedbd7e08
Revises: 0010_document_processing_events
Create Date: 2026-07-31 23:22:58.564173

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

import hospital_ai
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d6cedbd7e08"
down_revision: Union[str, None] = "0010_document_processing_events"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_processing_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("configuration_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint(
            "status in ('pending','running','completed','failed','cancelled')",
            name="ck_document_processing_runs_status",
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_processing_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_processing_runs_document_id"), ["document_id"], unique=False)

    op.create_table(
        "clinical_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("fact_type", sa.String(length=64), nullable=False),
        sa.Column("raw_value", hospital_ai.db.models.EncryptedText(), nullable=False),
        sa.Column("normalized_value", hospital_ai.db.models.EncryptedText(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("bounding_box", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint("status in ('unverified','confirmed','rejected')", name="ck_clinical_facts_status"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["document_processing_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clinical_facts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clinical_facts_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_clinical_facts_run_id"), ["run_id"], unique=False)

    op.create_table(
        "document_review_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("fact_id", sa.Uuid(), nullable=True),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column("original_value", hospital_ai.db.models.EncryptedText(), nullable=True),
        sa.Column("suggested_value", hospital_ai.db.models.EncryptedText(), nullable=True),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint(
            "review_status in ('pending','approved','rejected')", name="ck_document_review_items_status"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["clinical_facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["document_processing_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_review_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_review_items_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_review_items_fact_id"), ["fact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_review_items_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_review_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_review_items_run_id"))
        batch_op.drop_index(batch_op.f("ix_document_review_items_fact_id"))
        batch_op.drop_index(batch_op.f("ix_document_review_items_document_id"))

    op.drop_table("document_review_items")
    with op.batch_alter_table("clinical_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clinical_facts_run_id"))
        batch_op.drop_index(batch_op.f("ix_clinical_facts_document_id"))

    op.drop_table("clinical_facts")
    with op.batch_alter_table("document_processing_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_processing_runs_document_id"))

    op.drop_table("document_processing_runs")
    # ### end Alembic commands ###
