"""add_revision_generation_schema

Revision ID: cdi_v2_0001
Revises: 5a950640275c
Create Date: 2026-08-05 10:22:47.567641

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdi_v2_0001"
down_revision: Union[str, None] = "5a950640275c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claim_validation_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("validation_mode", sa.String(length=32), nullable=False),
        sa.Column("is_supported", sa.Boolean(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinical_timeline_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("clinical_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_evidence", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("reviewer_state", sa.String(length=32), nullable=True),
        sa.Column("conflict_state", sa.String(length=32), nullable=True),
        sa.Column("supersession_lineage", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clinical_timeline_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clinical_timeline_events_patient_id"), ["patient_id"], unique=False)

    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor_user_id", "scope", "key_hash", name="uq_idempotency_record"),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_idempotency_records_actor_user_id"), ["actor_user_id"], unique=False)

    op.create_table(
        "document_draft_heads",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("selected_pages", sa.JSON(), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_table(
        "document_extraction_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("engine_family", sa.String(length=64), nullable=False),
        sa.Column("engine_model", sa.String(length=64), nullable=False),
        sa.Column("engine_revision", sa.String(length=64), nullable=False),
        sa.Column("engine_config", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("peak_rss_mb", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_extraction_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_extraction_runs_document_id"), ["document_id"], unique=False)

    op.create_table(
        "document_revision_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("next_status", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("changed_page_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_revision_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_revision_events_document_id"), ["document_id"], unique=False)

    op.create_table(
        "document_revision_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status in ('submitted','approved','rejected','superseded')", name="ck_document_revision_sets_status"
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "revision_number", name="uq_document_revision_set_number"),
    )
    with op.batch_alter_table("document_revision_sets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_revision_sets_document_id"), ["document_id"], unique=False)

    op.create_table(
        "document_uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("expected_sha256", sa.String(length=64), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("quarantine_result", sa.Text(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    with op.batch_alter_table("document_uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_uploads_document_id"), ["document_id"], unique=False)

    op.create_table(
        "document_index_generations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("revision_set_id", sa.Uuid(), nullable=False),
        sa.Column("retry_of_generation_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="building"),
        sa.Column("revision_set_sha256", sa.String(length=64), nullable=False),
        sa.Column("generation_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_generation_id"],
            ["document_index_generations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_set_id"],
            ["document_revision_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_index_generations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_index_generations_document_id"), ["document_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_document_index_generations_revision_set_id"), ["revision_set_id"], unique=False
        )  # noqa: E501

    op.create_table(
        "document_page_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.Uuid(), nullable=True),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=True),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("revision_type", sa.String(length=32), nullable=False),
        sa.Column("raw_text_snapshot", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("edit_reason", sa.Text(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["document_extraction_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_revision_id"],
            ["document_page_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_page_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_page_revisions_document_id"), ["document_id"], unique=False)

    op.create_table(
        "document_revision_pages",
        sa.Column("revision_set_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("page_revision_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_revision_id"],
            ["document_page_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_set_id"],
            ["document_revision_sets.id"],
        ),
        sa.PrimaryKeyConstraint("revision_set_id", "page_number"),
    )
    with op.batch_alter_table("document_revision_pages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_revision_pages_page_revision_id"), ["page_revision_id"], unique=False
        )  # noqa: E501

    op.create_table(
        "generation_stage_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("generation_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("output_sha256", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["document_index_generations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generation_id", "stage", name="uq_generation_stage_result"),
    )
    with op.batch_alter_table("generation_stage_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_generation_stage_results_generation_id"), ["generation_id"], unique=False)

    op.create_table(
        "ocr_blocks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_revision_id", sa.Uuid(), nullable=False),
        sa.Column("text_start_offset", sa.Integer(), nullable=False),
        sa.Column("text_end_offset", sa.Integer(), nullable=False),
        sa.Column("polygon", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("alignment_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_revision_id"],
            ["document_page_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ocr_blocks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ocr_blocks_page_revision_id"), ["page_revision_id"], unique=False)

    op.create_table(
        "ocr_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("page_revision_id", sa.Uuid(), nullable=False),
        sa.Column("text_start_offset", sa.Integer(), nullable=False),
        sa.Column("text_end_offset", sa.Integer(), nullable=False),
        sa.Column("polygon", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("alignment_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["ocr_blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["page_revision_id"],
            ["document_page_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ocr_lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ocr_lines_block_id"), ["block_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ocr_lines_page_revision_id"), ["page_revision_id"], unique=False)

    op.create_table(
        "ocr_spans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("page_revision_id", sa.Uuid(), nullable=False),
        sa.Column("text_start_offset", sa.Integer(), nullable=False),
        sa.Column("text_end_offset", sa.Integer(), nullable=False),
        sa.Column("polygon", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("alignment_status", sa.String(length=32), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("source_engine_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["ocr_lines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["page_revision_id"],
            ["document_page_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ocr_spans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ocr_spans_line_id"), ["line_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ocr_spans_page_revision_id"), ["page_revision_id"], unique=False)

    with op.batch_alter_table("clinical_facts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("generation_id", sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f("ix_clinical_facts_generation_id"), ["generation_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_clinical_facts_generation_id", "document_index_generations", ["generation_id"], ["id"], use_alter=True
        )  # noqa: E501

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("generation_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("revision_set_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("page_revision_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("text_start_offset", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("text_end_offset", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("source_text_sha256", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("approval_state", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("bounding_boxes", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("access_tags", sa.JSON(), nullable=True))
        batch_op.drop_constraint("uq_document_chunk_index", type_="unique")
        batch_op.create_unique_constraint("uq_document_chunk_index", ["document_id", "generation_id", "chunk_index"])
        batch_op.create_index(batch_op.f("ix_document_chunks_generation_id"), ["generation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_chunks_page_revision_id"), ["page_revision_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_chunks_revision_set_id"), ["revision_set_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_document_chunks_page_revision_id",
            "document_page_revisions",
            ["page_revision_id"],
            ["id"],
            use_alter=True,
        )  # noqa: E501
        batch_op.create_foreign_key(
            "fk_document_chunks_generation_id", "document_index_generations", ["generation_id"], ["id"], use_alter=True
        )  # noqa: E501
        batch_op.create_foreign_key(
            "fk_document_chunks_revision_set_id", "document_revision_sets", ["revision_set_id"], ["id"], use_alter=True
        )  # noqa: E501

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("approved_revision_set_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("active_index_generation_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("finalized_upload_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("is_synthetic", sa.Boolean(), server_default="false", nullable=False))
        batch_op.add_column(sa.Column("retention_state", sa.String(length=32), nullable=True, server_default="active"))
        batch_op.create_foreign_key(
            "fk_documents_finalized_upload_id", "document_uploads", ["finalized_upload_id"], ["id"], use_alter=True
        )  # noqa: E501
        batch_op.create_foreign_key(
            "fk_documents_active_index_generation_id",
            "document_index_generations",
            ["active_index_generation_id"],
            ["id"],
            use_alter=True,
        )  # noqa: E501
        batch_op.create_foreign_key(
            "fk_documents_approved_revision_set_id",
            "document_revision_sets",
            ["approved_revision_set_id"],
            ["id"],
            use_alter=True,
        )  # noqa: E501

    op.execute("UPDATE documents SET retention_state = 'active' WHERE retention_state IS NULL")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column("retention_state", nullable=False, server_default=None)


    with op.batch_alter_table("retrieved_evidence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("generation_id", sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f("ix_retrieved_evidence_generation_id"), ["generation_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_retrieved_evidence_generation_id",
            "document_index_generations",
            ["generation_id"],
            ["id"],
            use_alter=True,
        )  # noqa: E501

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("retrieved_evidence", schema=None) as batch_op:
        batch_op.drop_constraint("fk_retrieved_evidence_generation_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_retrieved_evidence_generation_id"))
        batch_op.drop_column("generation_id")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint("fk_documents_active_index_generation_id", type_="foreignkey")
        batch_op.drop_constraint("fk_documents_finalized_upload_id", type_="foreignkey")
        batch_op.drop_constraint("fk_documents_approved_revision_set_id", type_="foreignkey")
        batch_op.drop_column("retention_state")
        batch_op.drop_column("is_synthetic")
        batch_op.drop_column("finalized_upload_id")
        batch_op.drop_column("active_index_generation_id")
        batch_op.drop_column("approved_revision_set_id")

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_constraint("fk_document_chunks_generation_id", type_="foreignkey")
        batch_op.drop_constraint("fk_document_chunks_revision_set_id", type_="foreignkey")
        batch_op.drop_constraint("fk_document_chunks_page_revision_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_document_chunks_revision_set_id"))
        batch_op.drop_index(batch_op.f("ix_document_chunks_page_revision_id"))
        batch_op.drop_index(batch_op.f("ix_document_chunks_generation_id"))
        batch_op.drop_column("access_tags")
        batch_op.drop_column("bounding_boxes")
        batch_op.drop_column("approval_state")
        batch_op.drop_column("source_text_sha256")
        batch_op.drop_column("text_end_offset")
        batch_op.drop_column("text_start_offset")
        batch_op.drop_column("page_revision_id")
        batch_op.drop_column("revision_set_id")
        batch_op.drop_column("generation_id")

    with op.batch_alter_table("clinical_facts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_clinical_facts_generation_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_clinical_facts_generation_id"))
        batch_op.drop_column("generation_id")

    with op.batch_alter_table("ocr_spans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ocr_spans_page_revision_id"))
        batch_op.drop_index(batch_op.f("ix_ocr_spans_line_id"))

    op.drop_table("ocr_spans")
    with op.batch_alter_table("ocr_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ocr_lines_page_revision_id"))
        batch_op.drop_index(batch_op.f("ix_ocr_lines_block_id"))

    op.drop_table("ocr_lines")
    with op.batch_alter_table("ocr_blocks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ocr_blocks_page_revision_id"))

    op.drop_table("ocr_blocks")
    with op.batch_alter_table("generation_stage_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_stage_results_generation_id"))

    op.drop_table("generation_stage_results")
    with op.batch_alter_table("document_revision_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_revision_pages_page_revision_id"))

    op.drop_table("document_revision_pages")
    with op.batch_alter_table("document_page_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_page_revisions_document_id"))

    op.drop_table("document_page_revisions")
    with op.batch_alter_table("document_index_generations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_index_generations_revision_set_id"))
        batch_op.drop_index(batch_op.f("ix_document_index_generations_document_id"))

    op.drop_table("document_index_generations")
    with op.batch_alter_table("document_uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_uploads_document_id"))

    op.drop_table("document_uploads")
    with op.batch_alter_table("document_revision_sets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_revision_sets_document_id"))

    op.drop_table("document_revision_sets")
    with op.batch_alter_table("document_revision_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_revision_events_document_id"))

    op.drop_table("document_revision_events")
    with op.batch_alter_table("document_extraction_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_extraction_runs_document_id"))

    op.drop_table("document_extraction_runs")
    op.drop_table("document_draft_heads")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_records_actor_user_id"))

    op.drop_table("idempotency_records")
    with op.batch_alter_table("clinical_timeline_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clinical_timeline_events_patient_id"))

    op.drop_table("clinical_timeline_events")
    op.drop_table("claim_validation_results")
    # ### end Alembic commands ###
